# Kong API Gateway Configuration with Kafka Integration
# This configuration sets up Kong as the entry point with Kafka for microservices communication

apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-kafka-config
  namespace: ecommerce
data:
  # Kong Gateway Configuration
  kong-database: "postgres"
  kong-pg-host: "kong-database"
  kong-pg-database: "kong"
  kong-pg-user: "kong"
  kong-pg-password: "kong"
  
  # Kong Proxy Configuration
  kong-proxy-access-log: "/dev/stdout"
  kong-admin-access-log: "/dev/stdout"
  kong-proxy-error-log: "/dev/stderr"
  kong-admin-error-log: "/dev/stderr"
  kong-admin-listen: "0.0.0.0:8001"
  kong-admin-gui-url: "http://localhost:8002"
  kong-admin-gui-listen: "0.0.0.0:8002"
  
  # Rate Limiting Configuration
  rate-limiting-minute: "100"
  rate-limiting-hour: "1000"
  rate-limiting-day: "10000"
  
  # Authentication Configuration
  jwt-secret: "your-jwt-secret-key"
  jwt-algorithm: "HS256"
  
  # CORS Configuration
  cors-origins: "*"
  cors-methods: "GET,POST,PUT,DELETE,OPTIONS"
  cors-headers: "Accept,Accept-Version,Content-Length,Content-MD5,Content-Type,Date,X-Auth-Token"
  
  # Kafka Integration Configuration
  kafka-bootstrap-servers: "kafka:9092"
  kafka-producer-acks: "all"
  kafka-producer-retries: "3"
  kafka-producer-batch-size: "16384"
  kafka-producer-linger-ms: "5"
  kafka-producer-buffer-memory: "33554432"
  
  # Service Discovery Configuration
  service-discovery-type: "dns"
  service-discovery-ttl: "30"
  
  # Health Check Configuration
  health-check-interval: "30"
  health-check-timeout: "5"
  health-check-healthy-threshold: "2"
  health-check-unhealthy-threshold: "3"
  
  # Logging Configuration
  log-level: "info"
  log-format: "json"
  log-file: "/var/log/kong/kong.log"
  
  # Metrics Configuration
  metrics-enabled: "true"
  metrics-prometheus-enabled: "true"
  metrics-prometheus-port: "9542"

