server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**
        - id: cart-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/cart/**
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/orders/**
        - id: payment-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/payments/**
        - id: notification-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/notifications/**
        - id: user-service-health
          uri: http://localhost:8081
          predicates:
            - Path=/health/users
        - id: product-service-health
          uri: http://localhost:8082
          predicates:
            - Path=/health/products
        - id: cart-service-health
          uri: http://localhost:8083
          predicates:
            - Path=/health/cart
        - id: order-service-health
          uri: http://localhost:8084
          predicates:
            - Path=/health/orders
        - id: payment-service-health
          uri: http://localhost:8085
          predicates:
            - Path=/health/payments
        - id: notification-service-health
          uri: http://localhost:8086
          predicates:
            - Path=/health/notifications
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: api-gateway-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    com.example.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
