FROM openjdk:17-jdk-slim

WORKDIR /app

# Copy Maven files
COPY pom.xml .
COPY src ./src

# Install Maven
RUN apt-get update && apt-get install -y maven && rm -rf /var/lib/apt/lists/*

# Build the application
RUN mvn clean package -DskipTests

# Run the application
EXPOSE 8083
CMD ["java", "-jar", "target/cart-service-0.0.1-SNAPSHOT.jar"]
