server:
  port: 8082

spring:
  application:
    name: product-service
  
  datasource:
    url: jdbc:mysql://mysql:3306/ecommerce_products
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  # Elasticsearch Configuration
  elasticsearch:
    uris: http://elasticsearch:9200
    connection-timeout: 10s
    socket-timeout: 30s
    max-connections: 100
    max-connections-per-route: 10
  
  # Redis Configuration
  data:
    redis:
      host: redis
      port: 6379
      password: 
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  
  # Enhanced Redis Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 900000  # 15 minutes in milliseconds
      cache-null-values: false
      enable-statistics: true
      key-prefix: "product:"
      use-key-prefix: true
  
      kafka:
        bootstrap-servers: kafka:9092
    consumer:
      group-id: product-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 5
      buffer-memory: 33554432

# Product Service Specific Configuration
product:
  elasticsearch:
    index:
      products: "products"
      categories: "categories"
    settings:
      number-of-shards: 1
      number-of-replicas: 0
      refresh-interval: "1s"
    search:
      timeout: 5s
      max-results: 100
      fuzzy-matching: true
      typo-correction: true
      suggestions-enabled: true
  cache:
    search-ttl: 900  # 15 minutes
    trending-ttl: 3600  # 1 hour
    suggestions-ttl: 1800  # 30 minutes
  performance:
    bulk-index-size: 1000
    search-cache-enabled: true
    analytics-enabled: true

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,elasticsearch
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  elasticsearch:
    health:
      enabled: true

logging:
  level:
    com.example.product: DEBUG
    org.springframework.kafka: INFO
    org.springframework.data.elasticsearch: DEBUG
    org.springframework.cache: DEBUG
    org.elasticsearch: INFO
