server:
  port: 8083

spring:
  application:
    name: cart-service
  
  datasource:
    url: jdbc:mysql://mysql:3306/ecommerce_cart
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  data:
    redis:
      host: redis
      port: 6379
      password: 
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 3000ms
        shutdown-timeout: 100ms
  # Enhanced Redis Cache Configuration for Cart Service
  cache:
    type: redis
    redis:
      time-to-live: 3600000  # 1 hour in milliseconds
      cache-null-values: false
      enable-statistics: true
      key-prefix: "cart:"
      use-key-prefix: true
  
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: cart-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Cart Service Specific Configuration
cart:
  cache:
    ttl: 3600  # 1 hour
    items-ttl: 1800  # 30 minutes
    session-ttl: 7200  # 2 hours
    product-ttl: 1800  # 30 minutes
  redis:
    max-memory: 256mb
    max-memory-policy: allkeys-lru
    compression: true
    serialization: json
  performance:
    batch-operations: true
    pipeline-operations: true
    cache-warming: true

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches,redis
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  cache:
    redis:
      enable-statistics: true

logging:
  level:
    com.example.cart: DEBUG
    org.springframework.kafka: INFO
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
